# Generated by Django 4.0.6 on 2022-08-23 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineCompany',
            fields=[
                ('_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('airline_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20, unique=True)),
                ('credit_card', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('landing_time', models.DateTimeField()),
                ('remaining_tickets', models.IntegerField()),
                ('airline_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airline_company', to='base.airlinecompany')),
                ('destination_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_country_id', to='base.country')),
                ('origin_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_country_id', to='base.country')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customerprofile')),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.flight')),
            ],
        ),
        migrations.AddField(
            model_name='airlinecompany',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.country'),
        ),
        migrations.AddField(
            model_name='airlinecompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('flight_id', 'customer_id'), name='unique_booking'),
        ),
    ]
