# Generated by Django 3.2.8 on 2022-07-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220705_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='airline',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airline_id',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='destination_country_id',
            new_name='destination_country',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='origin_country_id',
            new_name='origin_country',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='flight_id',
            new_name='flight',
        ),
    ]
