# Generated by Django 3.2.8 on 2022-07-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220705_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
    ]
