# Generated by Django 4.0.6 on 2022-07-09 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20220709_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='airline', to=settings.AUTH_USER_MODEL),
        ),
    ]
