# Generated by Django 4.0.6 on 2022-07-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_airline_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='credit_card',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_num',
            field=models.IntegerField(unique=True),
        ),
    ]
