# Generated by Django 4.0.6 on 2022-07-17 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_alter_customerprofile_credit_card_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airline',
            new_name='AirlineCompany',
        ),
        migrations.RenameField(
            model_name='airlinecompany',
            old_name='airline_id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='customer_id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flight_id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airline',
            new_name='airline_company',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_id',
            new_name='_id',
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='landing_time',
            field=models.DateTimeField(),
        ),
    ]
