# Generated by Django 4.0.6 on 2022-07-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_airline_airlinecompany_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='airlinecompany',
            constraint=models.UniqueConstraint(fields=('airline_name', 'user'), name='unique_airline_user'),
        ),
    ]
