# Generated by Django 4.0.6 on 2022-07-19 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_airlinecompany_unique_airline_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='airlinecompany',
            name='unique_airline_user',
        ),
        migrations.AlterField(
            model_name='airlinecompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
