# Generated by Django 4.0.6 on 2022-07-31 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_customerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airline_company', to='base.airlinecompany'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_country_id', to='base.country'),
        ),
    ]
